// --- DEFINISI TIPE KUSTOM ---
.type Address <: symbol

// --- DEKLARASI INPUT UNIVERSAL ---
.decl IncomingEvent(type:symbol, from:symbol, to:symbol, amount:float, extraData:symbol, timestamp:number, gasPrice: float, nonce:number, medianGas:float)
.input IncomingEvent(IO=stdin, delimiter="\t")

// --- MEMBUAT ULANG FAKTA SPESIFIK (Internal) ---
.decl ETHDepositInitiated(from:Address, to:Address, amount:float, extraData:symbol, timestamp:number, gasPrice: float, nonce:number, medianGas:float)

ETHDepositInitiated(as(from, Address), as(to, Address), amount, extraData, timestamp, gasPrice, nonce, medianGas) :-
    IncomingEvent("ETH", from, to, amount, extraData, timestamp, gasPrice, nonce, medianGas).

// --- DEKLARASI RULES ---
.decl HighValueEthDeposit(from:Address, to:Address, amount:float)
.output HighValueEthDeposit

.decl HighGasPrice(gasPrice:float, medianGas:float)
.output HighGasPrice

// --- ATURAN ANALISIS ---
HighValueEthDeposit(from, to, amount) :-
    ETHDepositInitiated(from, to, amount, _, _, _, _, _),
    amount >= 10000000000000000000.0. // Batas 10 ETH

HighGasPrice(gasPrice, medianGas) :-
    ETHDepositInitiated(_, _, _, _, _, gasPrice, _, medianGas),
    gasPrice > medianGas.
