// --- DEFINISI TIPE KUSTOM ---
.type Address <: symbol

// --- DEKLARASI INPUT UNIVERSAL ---
.decl IncomingEvent(type:symbol, p1:symbol, p2:symbol, p3:symbol, p4:symbol, p5:float, p6:symbol)
.input IncomingEvent(IO=stdin, delimiter="\t")

// --- MEMBUAT ULANG FAKTA SPESIFIK (Internal) ---
.decl ETHDepositInitiated(from:Address, to:Address, amount:float, extraData:symbol)

ETHDepositInitiated(as(from, Address), as(to, Address), amount, extraData) :-
    IncomingEvent("ETH", from, to, _, _, amount, extraData).

// --- DEKLARASI OUTPUT ---
.decl HighValueEthDeposit(from:Address, to:Address, amount:float)
.output HighValueEthDeposit

// --- ATURAN ANALISIS ---
HighValueEthDeposit(from, to, amount) :-
    ETHDepositInitiated(from, to, amount, _),
    amount <= 50000000000000000000.0. // Batas 50 ETH
